FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip

COPY . .

RUN pip install --no-cache-dir -e .

ARG BACKEND_PORT
ARG FRONTEND_PORT
ENV BACKEND_PORT=${BACKEND_PORT} \
    FRONTEND_PORT=${FRONTEND_PORT}

EXPOSE ${BACKEND_PORT}

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "${BACKEND_PORT}", "--reload"]
